### ISSUE TITLE
Compatibility issues with Parallels 10.2.1

### ISSUE THREAD

**Issue by fniephaus** [fniephaus/alfred-vmcontrol#1]
See http://www.alfredforum.com/topic/4080-vm-control/?p=36333

**Comment by queezythegreat** [comment]
Hi, the problem is related to `/usr/local/bin` not being included in the PATH. I fixed the problem with the following in _vm_list.py_ line 7:

```
os.environ['PATH'] = '/usr/local/bin:%s' % os.environ['PATH']
```

Mac OS X 10.10.4 and Parallels 10.2.1

**Comment by fniephaus** [comment]
Thanks for the info!
I will look into this next week :)

**Comment by queezythegreat** [comment]
The same issue occurs in the other python file, you should also add this fix there. I later figured that out...

**Comment by fniephaus** [comment]
Thanks for pointing that out, @queezythegreat.
I will push another update soon...
