### ISSUE TITLE
Not detecting VMs on VirtualBox 5.2

### ISSUE THREAD

**Issue by chriscarpenter12** [fniephaus/alfred-vmcontrol#11]
Just upgraded to 5.2 and typing `vm` doesn't seem to detect any of my VMs. Anyone else having this issue?

Error in debug log:
```
[2017-10-31 10:16:53][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "vm_list.py", line 11, in <module>
    vbox = mgr.vbox
AttributeError: 'VirtualBoxManager' object has no attribute 'vbox'
```

Not sure if this is an import error in python?

**Comment by fniephaus** [comment]
Hi @chriscarpenter12,
It looks like the underlying API of VirtualBox has changed from `5.1` to `5.2`.
Unfortunately, I currently don't have any cycles to work on this. Contributions welcome!

**Comment by chriscarpenter12** [comment]
That was my first thought as well, but wasn't sure. Thanks

**Comment by mz-bmcqueen** [comment]
Same problem here, but the current docs (http://download.virtualbox.org/virtualbox/SDKRef.pdf) still show this sample code:

`from vboxapi import VirtualBoxManager
mgr = VirtualBoxManager(None, None)
vbox = mgr.vbox
name = "Linux"
mach = vbox.findMachine(name)
session = mgr.getSessionObject(vbox)
progress = mach.launchVMProcess(session, "gui", "")
progress.waitForCompletion(-1)
mgr.closeMachineSession(session)`

Must be something else.
