### ISSUE TITLE
PD 10 support please

### ISSUE THREAD

**Issue by homever** [fniephaus/alfred-vmcontrol#3]
Parallels Desktop will suspend virtual machines and quit no matter what action you choose to execute, e.g., Pause, Stop...

**Comment by fniephaus** [comment]
Hi @homever,
Can you comment out/delete the following lines and try again?
https://github.com/fniephaus/alfred-vmcontrol/blob/5abaca26ec0bee5af32149eb298b2b8a96bfec6f/src/vm_control.py#L32-L35

**Comment by homever** [comment]
:dancer: It works :dancer: 

Now, all actions can be executed correctly.

**Comment by fniephaus** [comment]
Interesting, can you start a virtual machine and then run the following in your Terminal?

``` bash
/usr/local/bin/prlctl list --no-header
```

It should display a line for each running VM, does it or is the output empty?

**Comment by homever** [comment]
It does show a list of current running VMs.
Please let me know, if any further information you need. I'd be glad:D

**Comment by fniephaus** [comment]
Interesting, the code that you deleted should just check if anything is still running and then close Parallels. Does not seem to work properly. Thanks

**Comment by homever** [comment]
Oh btw, can you add text filter?
`vm` will list the existing VMs, e.g., windows 7, windows XP, then you continue typing 
`vm 7` will only give windows 7, and if you continue typing
`vm 7 suspend` will only give suspend action?

**Comment by fniephaus** [comment]
Sorry, but I currently do not have enough time to do it.
Please open another issue and I will work on this as soon as I can.
Thanks
