### ISSUE TITLE
VBoxManage: command not found

### ISSUE THREAD

**Issue by Kriechi** [fniephaus/alfred-vmcontrol#5]
I'm getting this error in the debug log when I try to start a VM:

`VBoxManage: command not found`

OSX 10.11
Virtualbox 5.0.10

**Comment by fniephaus** [comment]
Hi @Kriechi,
Have you installed the `VBoxManage` command line tool when installing VirtualBox?

**Comment by Kriechi** [comment]
Yes:

```
➜  ~  which VBoxManage
/usr/local/bin/VBoxManage
```

I'm not sure if Alfred loads my environment properly... I can only tell you that VBoxManage is available in my zsh inside a regular terminal.

**Comment by Kriechi** [comment]
I just checked what `$PATH` is set inside an Alfred Workflow script block:

```
/usr/bin:/bin:/usr/sbin:/sbin
```

which is not going to work... How can I get a proper `$PATH` inside Alfred scripts?

**Comment by marionava** [comment]
I had the same issue in debug mode. 
`[ERROR: alfred.workflow.output.script] sh: VBoxManage: command not found`
I run this on my iTerm and works fine
`VBoxManage startvm "Windows XP"`

But this is not working on vm_control.py is not working.

What can I do to fix this?

**Comment by Kriechi** [comment]
@marionava I just added this line above the python call:

``` bash
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
python vm_control.py ...
```

**Comment by marionava** [comment]
@Kriechi Thank you for your help. 

I changed the name of my virtual machine "WindowsXP" instead of "Windows XP" (without space) and then I added the PATH and now it is working perfect.

**Comment by asfork** [comment]
I had the same issue in debug mode. 
This is my `$PATH`:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
