### ISSUE TITLE
Not working on VirtualBox 5

### ISSUE THREAD

**Issue by marionava** [fniephaus/alfred-vmcontrol#7]
I installed VirtualBox 5.1.6 and is not working on that version. I'm getting this message 
<img width="590" alt="captura de pantalla 2016-10-06 a la s 15 06 44" src="https://cloud.githubusercontent.com/assets/478018/19168655/c33173ac-8bd6-11e6-8ce2-23e47b4f5395.png">

It would be great if you fix it!! 

Have a nice day!

**Comment by fniephaus** [comment]
Hi @marionava,
Unfortunately, I can't reproduce your problem. Could you provide a [debug log](https://www.alfredapp.com/help/workflows/advanced/debugger/)?

**Comment by ricardgf** [comment]
Maybe it's the same error as #9

**Comment by fniephaus** [comment]
Looks like it. Please reopen the issue if it happens again.
