### ISSUE TITLE
Issue with starting (Sierra + Parallels 11)

### ISSUE THREAD

**Issue by kitze** [fniephaus/alfred-vmcontrol#9]
I get the following error when trying to start it:

![](https://storage.jumpshare.com/preview/33wK03LDJTYiIub8J3U4Ax9hZCOhi9Bl-X1j-QROfyfkDssVqh4TALZW44WpPTMawfrt7ld-MvcfpFcNCf0WtFNlSmh0egFbdyHzE6LvoMAI4av1wcwKsmUDuTGzHRrg)

```
Starting debug for 'VM Control'

[2017-04-30 19:04:53][ERROR: input.scriptfilter] Code 1: 19:04:53 workflow.py:843 ERROR    0x80070005 (The object functionality is limited)
Traceback (most recent call last):
  File "/Users/kitze/Google Drive/Alfred.alfredpreferences/workflows/user.workflow.19676D70-E556-4249-9C43-E81065EFB38C/workflow/workflow.py", line 841, in run
    func(self)
  File "vm_list.py", line 26, in complete
    vm_list = get_vm_list()
  File "vm_list.py", line 112, in get_vm_list
    m.name, m.id, get_vm_state(m.state), '/Applications/VirtualBox.app'))
  File "/Applications/VirtualBox.app/Contents/MacOS/sdk/bindings/xpcom/python/xpcom/client/__init__.py", line 374, in __getattr__
    return getattr(interface, attr)
  File "/Applications/VirtualBox.app/Contents/MacOS/sdk/bindings/xpcom/python/xpcom/client/__init__.py", line 460, in __getattr__
    return XPTC_InvokeByIndex(self._comobj_, method_index, args)
Exception: 0x80070005 (The object functionality is limited)
```

Btw thank you for your great work, love this workflow!

**Comment by fniephaus** [comment]
Interesting, do you have VirtualBox installed? What version of Alfred are you using?

**Comment by kitze** [comment]
@fniephaus Latest version of alfred, I'm using it with Parallels, but I also have VirtualBox. Should I remove VirtualBox?

Thanks for the quick response!

**Comment by fniephaus** [comment]
I don't quite understand the error you encounter, but it certainly seems to be caused by VirtualBox. What happens when you rename your `VirtualBox.app` bundle?

**Comment by kitze** [comment]
@fniephaus I just deleted Virtualbox and it works fine now!

**Comment by fniephaus** [comment]
Mh, that doesn't solve the cause of the problem, but glad it now works for you.
I only use VirtualBox these days and haven't seen your error yet.
Thanks for bringing it up anyway

**Comment by kitze** [comment]
@fniephaus No problem, tnx for your help!

**Comment by ricardgf** [comment]
This is due an inaccessible machine in virtualbox.

You can solve it by modifying the get_vm_list function:


```
if vbox_available:
        for m in mgr.getArray(vbox, 'machines'):
            vmname = '<inaccessible>'
            try:
                vmname = m.name
            except Exception, e:
                None
            vmid = '';
            try:
                vmid = m.id
            except Exception, e:
                None
            if vmname == '<inaccessible>' or vmid == '':
                continue
            output.append(VMDetails(
                m.name, m.id, get_vm_state(m.state), '/Applications/VirtualBox.app'))

    return output
```

I don't know how to make a pull request so....
taken from: https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Main/webservice/samples/python/clienttest.py

**Comment by fniephaus** [comment]
Thanks, @ricardgf. You can [edit the file on GitHub](https://github.com/fniephaus/alfred-vmcontrol/edit/master/src/vm_list.py) and then open a pull request from there.
